Fix deploy workflow

diff --git a/.github/workflows/deploy-to-lambda.yml b/.github/workflows/deploy-to-lambda.yml
--- a/.github/workflows/deploy-to-lambda.yml
+++ b/.github/workflows/deploy-to-lambda.yml
@@ -8,7 +8,7 @@ on:
 #    branches:
 #      - main
 
-  # Trigger the workflow on a schedule
+  # Trigger the workflow on a schedule,
 #  schedule:
 #      - cron: '0 0 * * *' # Run every day at midnight UTC
 
@@ -32,26 +32,39 @@ jobs:
           # Install the AWS CLI
           curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
-          sudo ./aws/install
+          sudo ./aws/install --update
         if: success() # Only run this step if the previous steps were successful
+
+      - name: Configure AWS CLI
+        run: |
+          # AWS credentials for AWS CLI which are stored in GitHub Secrets of the repository
+          aws configure set region us-east-1
+          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       - name: 🚀 Deploy & Publish to AWS Lambda
         run: |
+          set -x  # Enable debugging
           LAMBDA_FUNCTION_NAME="Postgres2Parquet"
           SOURCE_FILE="lambda_function.py"
           QUERY_FILE="query.sql"
           
           # Deploy the Python file and query.sql to Lambda
           zip deployment.zip $SOURCE_FILE $QUERY_FILE
-          aws lambda update-function-code \
-            --function-name $LAMBDA_FUNCTION_NAME \
-            --zip-file fileb://deployment.zip
+          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://deployment.zip
+          
+          # Check the status of the update
+          while true; do
+            status=$(aws lambda get-function-configuration --function-name $LAMBDA_FUNCTION_NAME --query 'LastUpdateStatus' --output text)
+            if [ "$status" = "Successful" ]; then
+              break  # Exit the loop when the update is successful
+            elif [ "$status" = "Failed" ]; then
+              echo "Lambda function update failed."
+              exit 1
+            else
+              sleep 5  # Sleep for 5 seconds before checking again
+            fi
+          done
           
           # Publish a new version of the Lambda function
-          aws lambda publish-version \
-            --function-name $LAMBDA_FUNCTION_NAME
-
-        env:
-          # AWS credentials for AWS CLI which are stored in GitHub Secrets of the repository
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws lambda publish-version --function-name $LAMBDA_FUNCTION_NAME
